// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: bbq/collector/v1/collector_service.proto

package collectorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reading       *Reading               `protobuf:"bytes,1,opt,name=reading,proto3" json:"reading,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordRequest) Reset() {
	*x = RecordRequest{}
	mi := &file_bbq_collector_v1_collector_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordRequest) ProtoMessage() {}

func (x *RecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bbq_collector_v1_collector_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordRequest.ProtoReflect.Descriptor instead.
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return file_bbq_collector_v1_collector_service_proto_rawDescGZIP(), []int{0}
}

func (x *RecordRequest) GetReading() *Reading {
	if x != nil {
		return x.Reading
	}
	return nil
}

type RecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RecordedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordResponse) Reset() {
	*x = RecordResponse{}
	mi := &file_bbq_collector_v1_collector_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordResponse) ProtoMessage() {}

func (x *RecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bbq_collector_v1_collector_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordResponse.ProtoReflect.Descriptor instead.
func (*RecordResponse) Descriptor() ([]byte, []int) {
	return file_bbq_collector_v1_collector_service_proto_rawDescGZIP(), []int{1}
}

func (x *RecordResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RecordResponse) GetRecordedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RecordedAt
	}
	return nil
}

type SessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_bbq_collector_v1_collector_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bbq_collector_v1_collector_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_bbq_collector_v1_collector_service_proto_rawDescGZIP(), []int{2}
}

func (x *SessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_bbq_collector_v1_collector_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bbq_collector_v1_collector_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_bbq_collector_v1_collector_service_proto_rawDescGZIP(), []int{3}
}

func (x *SessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

var File_bbq_collector_v1_collector_service_proto protoreflect.FileDescriptor

const file_bbq_collector_v1_collector_service_proto_rawDesc = "" +
	"\n" +
	"(bbq/collector/v1/collector_service.proto\x12\x10bbq.collector.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1abbq/collector/v1/bbq.proto\"D\n" +
	"\rRecordRequest\x123\n" +
	"\areading\x18\x01 \x01(\v2\x19.bbq.collector.v1.ReadingR\areading\"l\n" +
	"\x0eRecordResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12;\n" +
	"\vrecorded_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"recordedAt\"$\n" +
	"\x0eSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"F\n" +
	"\x0fSessionResponse\x123\n" +
	"\asession\x18\x01 \x01(\v2\x19.bbq.collector.v1.SessionR\asession2\xb3\x01\n" +
	"\x10CollectorService\x12M\n" +
	"\x06Record\x12\x1f.bbq.collector.v1.RecordRequest\x1a .bbq.collector.v1.RecordResponse\"\x00\x12P\n" +
	"\aSession\x12 .bbq.collector.v1.SessionRequest\x1a!.bbq.collector.v1.SessionResponse\"\x00B\xd1\x01\n" +
	"\x14com.bbq.collector.v1B\x15CollectorServiceProtoP\x01Z@github.com/ssargent/public-apis/pkg/bbq/collector/v1;collectorv1\xa2\x02\x03BCX\xaa\x02\x10Bbq.Collector.V1\xca\x02\x10Bbq\\Collector\\V1\xe2\x02\x1cBbq\\Collector\\V1\\GPBMetadata\xea\x02\x12Bbq::Collector::V1b\x06proto3"

var (
	file_bbq_collector_v1_collector_service_proto_rawDescOnce sync.Once
	file_bbq_collector_v1_collector_service_proto_rawDescData []byte
)

func file_bbq_collector_v1_collector_service_proto_rawDescGZIP() []byte {
	file_bbq_collector_v1_collector_service_proto_rawDescOnce.Do(func() {
		file_bbq_collector_v1_collector_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bbq_collector_v1_collector_service_proto_rawDesc), len(file_bbq_collector_v1_collector_service_proto_rawDesc)))
	})
	return file_bbq_collector_v1_collector_service_proto_rawDescData
}

var file_bbq_collector_v1_collector_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bbq_collector_v1_collector_service_proto_goTypes = []any{
	(*RecordRequest)(nil),         // 0: bbq.collector.v1.RecordRequest
	(*RecordResponse)(nil),        // 1: bbq.collector.v1.RecordResponse
	(*SessionRequest)(nil),        // 2: bbq.collector.v1.SessionRequest
	(*SessionResponse)(nil),       // 3: bbq.collector.v1.SessionResponse
	(*Reading)(nil),               // 4: bbq.collector.v1.Reading
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*Session)(nil),               // 6: bbq.collector.v1.Session
}
var file_bbq_collector_v1_collector_service_proto_depIdxs = []int32{
	4, // 0: bbq.collector.v1.RecordRequest.reading:type_name -> bbq.collector.v1.Reading
	5, // 1: bbq.collector.v1.RecordResponse.recorded_at:type_name -> google.protobuf.Timestamp
	6, // 2: bbq.collector.v1.SessionResponse.session:type_name -> bbq.collector.v1.Session
	0, // 3: bbq.collector.v1.CollectorService.Record:input_type -> bbq.collector.v1.RecordRequest
	2, // 4: bbq.collector.v1.CollectorService.Session:input_type -> bbq.collector.v1.SessionRequest
	1, // 5: bbq.collector.v1.CollectorService.Record:output_type -> bbq.collector.v1.RecordResponse
	3, // 6: bbq.collector.v1.CollectorService.Session:output_type -> bbq.collector.v1.SessionResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bbq_collector_v1_collector_service_proto_init() }
func file_bbq_collector_v1_collector_service_proto_init() {
	if File_bbq_collector_v1_collector_service_proto != nil {
		return
	}
	file_bbq_collector_v1_bbq_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bbq_collector_v1_collector_service_proto_rawDesc), len(file_bbq_collector_v1_collector_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bbq_collector_v1_collector_service_proto_goTypes,
		DependencyIndexes: file_bbq_collector_v1_collector_service_proto_depIdxs,
		MessageInfos:      file_bbq_collector_v1_collector_service_proto_msgTypes,
	}.Build()
	File_bbq_collector_v1_collector_service_proto = out.File
	file_bbq_collector_v1_collector_service_proto_goTypes = nil
	file_bbq_collector_v1_collector_service_proto_depIdxs = nil
}
