// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: worldbuilder/entity/v1/entity.proto

package entityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttributeDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Wbatn         string                 `protobuf:"bytes,2,opt,name=wbatn,proto3" json:"wbatn,omitempty"`
	AttributeName string                 `protobuf:"bytes,3,opt,name=attribute_name,json=attributeName,proto3" json:"attribute_name,omitempty"`
	Label         string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	DataType      string                 `protobuf:"bytes,5,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeDefinition) Reset() {
	*x = AttributeDefinition{}
	mi := &file_worldbuilder_entity_v1_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeDefinition) ProtoMessage() {}

func (x *AttributeDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_worldbuilder_entity_v1_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeDefinition.ProtoReflect.Descriptor instead.
func (*AttributeDefinition) Descriptor() ([]byte, []int) {
	return file_worldbuilder_entity_v1_entity_proto_rawDescGZIP(), []int{0}
}

func (x *AttributeDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AttributeDefinition) GetWbatn() string {
	if x != nil {
		return x.Wbatn
	}
	return ""
}

func (x *AttributeDefinition) GetAttributeName() string {
	if x != nil {
		return x.AttributeName
	}
	return ""
}

func (x *AttributeDefinition) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AttributeDefinition) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *AttributeDefinition) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AttributeDefinition) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type TypeAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wbatn         string                 `protobuf:"bytes,1,opt,name=wbatn,proto3" json:"wbatn,omitempty"`
	AttributeName string                 `protobuf:"bytes,2,opt,name=attribute_name,json=attributeName,proto3" json:"attribute_name,omitempty"`
	Ordinal       int32                  `protobuf:"varint,3,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	IsRequired    bool                   `protobuf:"varint,4,opt,name=is_required,json=isRequired,proto3" json:"is_required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeAttribute) Reset() {
	*x = TypeAttribute{}
	mi := &file_worldbuilder_entity_v1_entity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeAttribute) ProtoMessage() {}

func (x *TypeAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_worldbuilder_entity_v1_entity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeAttribute.ProtoReflect.Descriptor instead.
func (*TypeAttribute) Descriptor() ([]byte, []int) {
	return file_worldbuilder_entity_v1_entity_proto_rawDescGZIP(), []int{1}
}

func (x *TypeAttribute) GetWbatn() string {
	if x != nil {
		return x.Wbatn
	}
	return ""
}

func (x *TypeAttribute) GetAttributeName() string {
	if x != nil {
		return x.AttributeName
	}
	return ""
}

func (x *TypeAttribute) GetOrdinal() int32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *TypeAttribute) GetIsRequired() bool {
	if x != nil {
		return x.IsRequired
	}
	return false
}

type TypeParent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TypeId          string                 `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Wbtn            string                 `protobuf:"bytes,2,opt,name=wbtn,proto3" json:"wbtn,omitempty"`
	TypeName        string                 `protobuf:"bytes,3,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	TypeDescription string                 `protobuf:"bytes,4,opt,name=type_description,json=typeDescription,proto3" json:"type_description,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TypeParent) Reset() {
	*x = TypeParent{}
	mi := &file_worldbuilder_entity_v1_entity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeParent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeParent) ProtoMessage() {}

func (x *TypeParent) ProtoReflect() protoreflect.Message {
	mi := &file_worldbuilder_entity_v1_entity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeParent.ProtoReflect.Descriptor instead.
func (*TypeParent) Descriptor() ([]byte, []int) {
	return file_worldbuilder_entity_v1_entity_proto_rawDescGZIP(), []int{2}
}

func (x *TypeParent) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *TypeParent) GetWbtn() string {
	if x != nil {
		return x.Wbtn
	}
	return ""
}

func (x *TypeParent) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *TypeParent) GetTypeDescription() string {
	if x != nil {
		return x.TypeDescription
	}
	return ""
}

type Type struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TypeId          string                 `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Wbtn            string                 `protobuf:"bytes,2,opt,name=wbtn,proto3" json:"wbtn,omitempty"`
	TypeName        string                 `protobuf:"bytes,3,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	TypeDescription string                 `protobuf:"bytes,4,opt,name=type_description,json=typeDescription,proto3" json:"type_description,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Parent          *TypeParent            `protobuf:"bytes,7,opt,name=parent,proto3" json:"parent,omitempty"`
	Attributes      []*TypeAttribute       `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Type) Reset() {
	*x = Type{}
	mi := &file_worldbuilder_entity_v1_entity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_worldbuilder_entity_v1_entity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_worldbuilder_entity_v1_entity_proto_rawDescGZIP(), []int{3}
}

func (x *Type) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *Type) GetWbtn() string {
	if x != nil {
		return x.Wbtn
	}
	return ""
}

func (x *Type) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *Type) GetTypeDescription() string {
	if x != nil {
		return x.TypeDescription
	}
	return ""
}

func (x *Type) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Type) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Type) GetParent() *TypeParent {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *Type) GetAttributes() []*TypeAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type EntityAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityAttribute) Reset() {
	*x = EntityAttribute{}
	mi := &file_worldbuilder_entity_v1_entity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityAttribute) ProtoMessage() {}

func (x *EntityAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_worldbuilder_entity_v1_entity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityAttribute.ProtoReflect.Descriptor instead.
func (*EntityAttribute) Descriptor() ([]byte, []int) {
	return file_worldbuilder_entity_v1_entity_proto_rawDescGZIP(), []int{4}
}

func (x *EntityAttribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityAttribute) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EntityAttribute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type EntityParent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityName    string                 `protobuf:"bytes,2,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`
	ResourceName  string                 `protobuf:"bytes,3,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	TypeName      string                 `protobuf:"bytes,4,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityParent) Reset() {
	*x = EntityParent{}
	mi := &file_worldbuilder_entity_v1_entity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityParent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityParent) ProtoMessage() {}

func (x *EntityParent) ProtoReflect() protoreflect.Message {
	mi := &file_worldbuilder_entity_v1_entity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityParent.ProtoReflect.Descriptor instead.
func (*EntityParent) Descriptor() ([]byte, []int) {
	return file_worldbuilder_entity_v1_entity_proto_rawDescGZIP(), []int{5}
}

func (x *EntityParent) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *EntityParent) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

func (x *EntityParent) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *EntityParent) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

type EntityType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeId        string                 `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	TypeName      string                 `protobuf:"bytes,2,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityType) Reset() {
	*x = EntityType{}
	mi := &file_worldbuilder_entity_v1_entity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityType) ProtoMessage() {}

func (x *EntityType) ProtoReflect() protoreflect.Message {
	mi := &file_worldbuilder_entity_v1_entity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityType.ProtoReflect.Descriptor instead.
func (*EntityType) Descriptor() ([]byte, []int) {
	return file_worldbuilder_entity_v1_entity_proto_rawDescGZIP(), []int{6}
}

func (x *EntityType) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *EntityType) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ResourceName  string                 `protobuf:"bytes,2,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Parent        *EntityParent          `protobuf:"bytes,7,opt,name=parent,proto3" json:"parent,omitempty"`
	Type          *EntityType            `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	Attributes    []*EntityAttribute     `protobuf:"bytes,9,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_worldbuilder_entity_v1_entity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_worldbuilder_entity_v1_entity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_worldbuilder_entity_v1_entity_proto_rawDescGZIP(), []int{7}
}

func (x *Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entity) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *Entity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Entity) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Entity) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Entity) GetParent() *EntityParent {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *Entity) GetType() *EntityType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Entity) GetAttributes() []*EntityAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type EntityInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceName  string                 `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ParentWbrn    string                 `protobuf:"bytes,4,opt,name=parent_wbrn,json=parentWbrn,proto3" json:"parent_wbrn,omitempty"`
	TypeName      string                 `protobuf:"bytes,5,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	Attributes    []*EntityAttribute     `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityInput) Reset() {
	*x = EntityInput{}
	mi := &file_worldbuilder_entity_v1_entity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityInput) ProtoMessage() {}

func (x *EntityInput) ProtoReflect() protoreflect.Message {
	mi := &file_worldbuilder_entity_v1_entity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityInput.ProtoReflect.Descriptor instead.
func (*EntityInput) Descriptor() ([]byte, []int) {
	return file_worldbuilder_entity_v1_entity_proto_rawDescGZIP(), []int{8}
}

func (x *EntityInput) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *EntityInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EntityInput) GetParentWbrn() string {
	if x != nil {
		return x.ParentWbrn
	}
	return ""
}

func (x *EntityInput) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *EntityInput) GetAttributes() []*EntityAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeName      *string                `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3,oneof" json:"type_name,omitempty"`
	ParentWbrn    *string                `protobuf:"bytes,2,opt,name=parent_wbrn,json=parentWbrn,proto3,oneof" json:"parent_wbrn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_worldbuilder_entity_v1_entity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_worldbuilder_entity_v1_entity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_worldbuilder_entity_v1_entity_proto_rawDescGZIP(), []int{9}
}

func (x *Filter) GetTypeName() string {
	if x != nil && x.TypeName != nil {
		return *x.TypeName
	}
	return ""
}

func (x *Filter) GetParentWbrn() string {
	if x != nil && x.ParentWbrn != nil {
		return *x.ParentWbrn
	}
	return ""
}

var File_worldbuilder_entity_v1_entity_proto protoreflect.FileDescriptor

const file_worldbuilder_entity_v1_entity_proto_rawDesc = "" +
	"\n" +
	"#worldbuilder/entity/v1/entity.proto\x12\x16worldbuilder.entity.v1\"\xd3\x01\n" +
	"\x13AttributeDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05wbatn\x18\x02 \x01(\tR\x05wbatn\x12%\n" +
	"\x0eattribute_name\x18\x03 \x01(\tR\rattributeName\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x1b\n" +
	"\tdata_type\x18\x05 \x01(\tR\bdataType\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"\x87\x01\n" +
	"\rTypeAttribute\x12\x14\n" +
	"\x05wbatn\x18\x01 \x01(\tR\x05wbatn\x12%\n" +
	"\x0eattribute_name\x18\x02 \x01(\tR\rattributeName\x12\x18\n" +
	"\aordinal\x18\x03 \x01(\x05R\aordinal\x12\x1f\n" +
	"\vis_required\x18\x04 \x01(\bR\n" +
	"isRequired\"\x81\x01\n" +
	"\n" +
	"TypeParent\x12\x17\n" +
	"\atype_id\x18\x01 \x01(\tR\x06typeId\x12\x12\n" +
	"\x04wbtn\x18\x02 \x01(\tR\x04wbtn\x12\x1b\n" +
	"\ttype_name\x18\x03 \x01(\tR\btypeName\x12)\n" +
	"\x10type_description\x18\x04 \x01(\tR\x0ftypeDescription\"\xbc\x02\n" +
	"\x04Type\x12\x17\n" +
	"\atype_id\x18\x01 \x01(\tR\x06typeId\x12\x12\n" +
	"\x04wbtn\x18\x02 \x01(\tR\x04wbtn\x12\x1b\n" +
	"\ttype_name\x18\x03 \x01(\tR\btypeName\x12)\n" +
	"\x10type_description\x18\x04 \x01(\tR\x0ftypeDescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\x12:\n" +
	"\x06parent\x18\a \x01(\v2\".worldbuilder.entity.v1.TypeParentR\x06parent\x12E\n" +
	"\n" +
	"attributes\x18\b \x03(\v2%.worldbuilder.entity.v1.TypeAttributeR\n" +
	"attributes\"O\n" +
	"\x0fEntityAttribute\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\x8e\x01\n" +
	"\fEntityParent\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_name\x18\x02 \x01(\tR\n" +
	"entityName\x12#\n" +
	"\rresource_name\x18\x03 \x01(\tR\fresourceName\x12\x1b\n" +
	"\ttype_name\x18\x04 \x01(\tR\btypeName\"B\n" +
	"\n" +
	"EntityType\x12\x17\n" +
	"\atype_id\x18\x01 \x01(\tR\x06typeId\x12\x1b\n" +
	"\ttype_name\x18\x02 \x01(\tR\btypeName\"\xf0\x02\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rresource_name\x18\x02 \x01(\tR\fresourceName\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12<\n" +
	"\x06parent\x18\a \x01(\v2$.worldbuilder.entity.v1.EntityParentR\x06parent\x126\n" +
	"\x04type\x18\b \x01(\v2\".worldbuilder.entity.v1.EntityTypeR\x04type\x12G\n" +
	"\n" +
	"attributes\x18\t \x03(\v2'.worldbuilder.entity.v1.EntityAttributeR\n" +
	"attributes\"\xef\x01\n" +
	"\vEntityInput\x12#\n" +
	"\rresource_name\x18\x01 \x01(\tR\fresourceName\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vparent_wbrn\x18\x04 \x01(\tR\n" +
	"parentWbrn\x12\x1b\n" +
	"\ttype_name\x18\x05 \x01(\tR\btypeName\x12G\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2'.worldbuilder.entity.v1.EntityAttributeR\n" +
	"attributes\"n\n" +
	"\x06Filter\x12 \n" +
	"\ttype_name\x18\x01 \x01(\tH\x00R\btypeName\x88\x01\x01\x12$\n" +
	"\vparent_wbrn\x18\x02 \x01(\tH\x01R\n" +
	"parentWbrn\x88\x01\x01B\f\n" +
	"\n" +
	"_type_nameB\x0e\n" +
	"\f_parent_wbrnB\xe8\x01\n" +
	"\x1acom.worldbuilder.entity.v1B\vEntityProtoP\x01ZCgithub.com/ssargent/public-apis/pkg/worldbuilder/entity/v1;entityv1\xa2\x02\x03WEX\xaa\x02\x16Worldbuilder.Entity.V1\xca\x02\x16Worldbuilder\\Entity\\V1\xe2\x02\"Worldbuilder\\Entity\\V1\\GPBMetadata\xea\x02\x18Worldbuilder::Entity::V1b\x06proto3"

var (
	file_worldbuilder_entity_v1_entity_proto_rawDescOnce sync.Once
	file_worldbuilder_entity_v1_entity_proto_rawDescData []byte
)

func file_worldbuilder_entity_v1_entity_proto_rawDescGZIP() []byte {
	file_worldbuilder_entity_v1_entity_proto_rawDescOnce.Do(func() {
		file_worldbuilder_entity_v1_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worldbuilder_entity_v1_entity_proto_rawDesc), len(file_worldbuilder_entity_v1_entity_proto_rawDesc)))
	})
	return file_worldbuilder_entity_v1_entity_proto_rawDescData
}

var file_worldbuilder_entity_v1_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_worldbuilder_entity_v1_entity_proto_goTypes = []any{
	(*AttributeDefinition)(nil), // 0: worldbuilder.entity.v1.AttributeDefinition
	(*TypeAttribute)(nil),       // 1: worldbuilder.entity.v1.TypeAttribute
	(*TypeParent)(nil),          // 2: worldbuilder.entity.v1.TypeParent
	(*Type)(nil),                // 3: worldbuilder.entity.v1.Type
	(*EntityAttribute)(nil),     // 4: worldbuilder.entity.v1.EntityAttribute
	(*EntityParent)(nil),        // 5: worldbuilder.entity.v1.EntityParent
	(*EntityType)(nil),          // 6: worldbuilder.entity.v1.EntityType
	(*Entity)(nil),              // 7: worldbuilder.entity.v1.Entity
	(*EntityInput)(nil),         // 8: worldbuilder.entity.v1.EntityInput
	(*Filter)(nil),              // 9: worldbuilder.entity.v1.Filter
}
var file_worldbuilder_entity_v1_entity_proto_depIdxs = []int32{
	2, // 0: worldbuilder.entity.v1.Type.parent:type_name -> worldbuilder.entity.v1.TypeParent
	1, // 1: worldbuilder.entity.v1.Type.attributes:type_name -> worldbuilder.entity.v1.TypeAttribute
	5, // 2: worldbuilder.entity.v1.Entity.parent:type_name -> worldbuilder.entity.v1.EntityParent
	6, // 3: worldbuilder.entity.v1.Entity.type:type_name -> worldbuilder.entity.v1.EntityType
	4, // 4: worldbuilder.entity.v1.Entity.attributes:type_name -> worldbuilder.entity.v1.EntityAttribute
	4, // 5: worldbuilder.entity.v1.EntityInput.attributes:type_name -> worldbuilder.entity.v1.EntityAttribute
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_worldbuilder_entity_v1_entity_proto_init() }
func file_worldbuilder_entity_v1_entity_proto_init() {
	if File_worldbuilder_entity_v1_entity_proto != nil {
		return
	}
	file_worldbuilder_entity_v1_entity_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worldbuilder_entity_v1_entity_proto_rawDesc), len(file_worldbuilder_entity_v1_entity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_worldbuilder_entity_v1_entity_proto_goTypes,
		DependencyIndexes: file_worldbuilder_entity_v1_entity_proto_depIdxs,
		MessageInfos:      file_worldbuilder_entity_v1_entity_proto_msgTypes,
	}.Build()
	File_worldbuilder_entity_v1_entity_proto = out.File
	file_worldbuilder_entity_v1_entity_proto_goTypes = nil
	file_worldbuilder_entity_v1_entity_proto_depIdxs = nil
}
