// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: worldbuilder/entity/v1/entity_service.proto

package entityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityRequest) Reset() {
	*x = GetEntityRequest{}
	mi := &file_worldbuilder_entity_v1_entity_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityRequest) ProtoMessage() {}

func (x *GetEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worldbuilder_entity_v1_entity_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityRequest.ProtoReflect.Descriptor instead.
func (*GetEntityRequest) Descriptor() ([]byte, []int) {
	return file_worldbuilder_entity_v1_entity_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetEntityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *Entity                `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityResponse) Reset() {
	*x = GetEntityResponse{}
	mi := &file_worldbuilder_entity_v1_entity_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityResponse) ProtoMessage() {}

func (x *GetEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worldbuilder_entity_v1_entity_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityResponse.ProtoReflect.Descriptor instead.
func (*GetEntityResponse) Descriptor() ([]byte, []int) {
	return file_worldbuilder_entity_v1_entity_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetEntityResponse) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type GetEntitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Criteria      *Filter                `protobuf:"bytes,1,opt,name=criteria,proto3" json:"criteria,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntitiesRequest) Reset() {
	*x = GetEntitiesRequest{}
	mi := &file_worldbuilder_entity_v1_entity_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntitiesRequest) ProtoMessage() {}

func (x *GetEntitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worldbuilder_entity_v1_entity_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntitiesRequest.ProtoReflect.Descriptor instead.
func (*GetEntitiesRequest) Descriptor() ([]byte, []int) {
	return file_worldbuilder_entity_v1_entity_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetEntitiesRequest) GetCriteria() *Filter {
	if x != nil {
		return x.Criteria
	}
	return nil
}

type GetEntitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Criteria      *Filter                `protobuf:"bytes,1,opt,name=criteria,proto3" json:"criteria,omitempty"`
	Entities      []*Entity              `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntitiesResponse) Reset() {
	*x = GetEntitiesResponse{}
	mi := &file_worldbuilder_entity_v1_entity_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntitiesResponse) ProtoMessage() {}

func (x *GetEntitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worldbuilder_entity_v1_entity_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntitiesResponse.ProtoReflect.Descriptor instead.
func (*GetEntitiesResponse) Descriptor() ([]byte, []int) {
	return file_worldbuilder_entity_v1_entity_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetEntitiesResponse) GetCriteria() *Filter {
	if x != nil {
		return x.Criteria
	}
	return nil
}

func (x *GetEntitiesResponse) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type CreateTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *Type                  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTypeRequest) Reset() {
	*x = CreateTypeRequest{}
	mi := &file_worldbuilder_entity_v1_entity_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTypeRequest) ProtoMessage() {}

func (x *CreateTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worldbuilder_entity_v1_entity_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTypeRequest.ProtoReflect.Descriptor instead.
func (*CreateTypeRequest) Descriptor() ([]byte, []int) {
	return file_worldbuilder_entity_v1_entity_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTypeRequest) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

type CreateTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *Type                  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTypeResponse) Reset() {
	*x = CreateTypeResponse{}
	mi := &file_worldbuilder_entity_v1_entity_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTypeResponse) ProtoMessage() {}

func (x *CreateTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worldbuilder_entity_v1_entity_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTypeResponse.ProtoReflect.Descriptor instead.
func (*CreateTypeResponse) Descriptor() ([]byte, []int) {
	return file_worldbuilder_entity_v1_entity_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTypeResponse) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

type CreateEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *EntityInput           `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEntityRequest) Reset() {
	*x = CreateEntityRequest{}
	mi := &file_worldbuilder_entity_v1_entity_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntityRequest) ProtoMessage() {}

func (x *CreateEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worldbuilder_entity_v1_entity_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntityRequest.ProtoReflect.Descriptor instead.
func (*CreateEntityRequest) Descriptor() ([]byte, []int) {
	return file_worldbuilder_entity_v1_entity_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateEntityRequest) GetEntity() *EntityInput {
	if x != nil {
		return x.Entity
	}
	return nil
}

type CreateEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *Entity                `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEntityResponse) Reset() {
	*x = CreateEntityResponse{}
	mi := &file_worldbuilder_entity_v1_entity_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntityResponse) ProtoMessage() {}

func (x *CreateEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worldbuilder_entity_v1_entity_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntityResponse.ProtoReflect.Descriptor instead.
func (*CreateEntityResponse) Descriptor() ([]byte, []int) {
	return file_worldbuilder_entity_v1_entity_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateEntityResponse) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

var File_worldbuilder_entity_v1_entity_service_proto protoreflect.FileDescriptor

const file_worldbuilder_entity_v1_entity_service_proto_rawDesc = "" +
	"\n" +
	"+worldbuilder/entity/v1/entity_service.proto\x12\x16worldbuilder.entity.v1\x1a#worldbuilder/entity/v1/entity.proto\"\"\n" +
	"\x10GetEntityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x11GetEntityResponse\x126\n" +
	"\x06entity\x18\x01 \x01(\v2\x1e.worldbuilder.entity.v1.EntityR\x06entity\"P\n" +
	"\x12GetEntitiesRequest\x12:\n" +
	"\bcriteria\x18\x01 \x01(\v2\x1e.worldbuilder.entity.v1.FilterR\bcriteria\"\x8d\x01\n" +
	"\x13GetEntitiesResponse\x12:\n" +
	"\bcriteria\x18\x01 \x01(\v2\x1e.worldbuilder.entity.v1.FilterR\bcriteria\x12:\n" +
	"\bentities\x18\x02 \x03(\v2\x1e.worldbuilder.entity.v1.EntityR\bentities\"E\n" +
	"\x11CreateTypeRequest\x120\n" +
	"\x04type\x18\x01 \x01(\v2\x1c.worldbuilder.entity.v1.TypeR\x04type\"F\n" +
	"\x12CreateTypeResponse\x120\n" +
	"\x04type\x18\x01 \x01(\v2\x1c.worldbuilder.entity.v1.TypeR\x04type\"R\n" +
	"\x13CreateEntityRequest\x12;\n" +
	"\x06entity\x18\x01 \x01(\v2#.worldbuilder.entity.v1.EntityInputR\x06entity\"N\n" +
	"\x14CreateEntityResponse\x126\n" +
	"\x06entity\x18\x01 \x01(\v2\x1e.worldbuilder.entity.v1.EntityR\x06entity2\xb1\x03\n" +
	"\rEntityService\x12b\n" +
	"\tGetEntity\x12(.worldbuilder.entity.v1.GetEntityRequest\x1a).worldbuilder.entity.v1.GetEntityResponse\"\x00\x12h\n" +
	"\vGetEntities\x12*.worldbuilder.entity.v1.GetEntitiesRequest\x1a+.worldbuilder.entity.v1.GetEntitiesResponse\"\x00\x12e\n" +
	"\n" +
	"CreateType\x12).worldbuilder.entity.v1.CreateTypeRequest\x1a*.worldbuilder.entity.v1.CreateTypeResponse\"\x00\x12k\n" +
	"\fCreateEntity\x12+.worldbuilder.entity.v1.CreateEntityRequest\x1a,.worldbuilder.entity.v1.CreateEntityResponse\"\x00B\xef\x01\n" +
	"\x1acom.worldbuilder.entity.v1B\x12EntityServiceProtoP\x01ZCgithub.com/ssargent/public-apis/pkg/worldbuilder/entity/v1;entityv1\xa2\x02\x03WEX\xaa\x02\x16Worldbuilder.Entity.V1\xca\x02\x16Worldbuilder\\Entity\\V1\xe2\x02\"Worldbuilder\\Entity\\V1\\GPBMetadata\xea\x02\x18Worldbuilder::Entity::V1b\x06proto3"

var (
	file_worldbuilder_entity_v1_entity_service_proto_rawDescOnce sync.Once
	file_worldbuilder_entity_v1_entity_service_proto_rawDescData []byte
)

func file_worldbuilder_entity_v1_entity_service_proto_rawDescGZIP() []byte {
	file_worldbuilder_entity_v1_entity_service_proto_rawDescOnce.Do(func() {
		file_worldbuilder_entity_v1_entity_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worldbuilder_entity_v1_entity_service_proto_rawDesc), len(file_worldbuilder_entity_v1_entity_service_proto_rawDesc)))
	})
	return file_worldbuilder_entity_v1_entity_service_proto_rawDescData
}

var file_worldbuilder_entity_v1_entity_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_worldbuilder_entity_v1_entity_service_proto_goTypes = []any{
	(*GetEntityRequest)(nil),     // 0: worldbuilder.entity.v1.GetEntityRequest
	(*GetEntityResponse)(nil),    // 1: worldbuilder.entity.v1.GetEntityResponse
	(*GetEntitiesRequest)(nil),   // 2: worldbuilder.entity.v1.GetEntitiesRequest
	(*GetEntitiesResponse)(nil),  // 3: worldbuilder.entity.v1.GetEntitiesResponse
	(*CreateTypeRequest)(nil),    // 4: worldbuilder.entity.v1.CreateTypeRequest
	(*CreateTypeResponse)(nil),   // 5: worldbuilder.entity.v1.CreateTypeResponse
	(*CreateEntityRequest)(nil),  // 6: worldbuilder.entity.v1.CreateEntityRequest
	(*CreateEntityResponse)(nil), // 7: worldbuilder.entity.v1.CreateEntityResponse
	(*Entity)(nil),               // 8: worldbuilder.entity.v1.Entity
	(*Filter)(nil),               // 9: worldbuilder.entity.v1.Filter
	(*Type)(nil),                 // 10: worldbuilder.entity.v1.Type
	(*EntityInput)(nil),          // 11: worldbuilder.entity.v1.EntityInput
}
var file_worldbuilder_entity_v1_entity_service_proto_depIdxs = []int32{
	8,  // 0: worldbuilder.entity.v1.GetEntityResponse.entity:type_name -> worldbuilder.entity.v1.Entity
	9,  // 1: worldbuilder.entity.v1.GetEntitiesRequest.criteria:type_name -> worldbuilder.entity.v1.Filter
	9,  // 2: worldbuilder.entity.v1.GetEntitiesResponse.criteria:type_name -> worldbuilder.entity.v1.Filter
	8,  // 3: worldbuilder.entity.v1.GetEntitiesResponse.entities:type_name -> worldbuilder.entity.v1.Entity
	10, // 4: worldbuilder.entity.v1.CreateTypeRequest.type:type_name -> worldbuilder.entity.v1.Type
	10, // 5: worldbuilder.entity.v1.CreateTypeResponse.type:type_name -> worldbuilder.entity.v1.Type
	11, // 6: worldbuilder.entity.v1.CreateEntityRequest.entity:type_name -> worldbuilder.entity.v1.EntityInput
	8,  // 7: worldbuilder.entity.v1.CreateEntityResponse.entity:type_name -> worldbuilder.entity.v1.Entity
	0,  // 8: worldbuilder.entity.v1.EntityService.GetEntity:input_type -> worldbuilder.entity.v1.GetEntityRequest
	2,  // 9: worldbuilder.entity.v1.EntityService.GetEntities:input_type -> worldbuilder.entity.v1.GetEntitiesRequest
	4,  // 10: worldbuilder.entity.v1.EntityService.CreateType:input_type -> worldbuilder.entity.v1.CreateTypeRequest
	6,  // 11: worldbuilder.entity.v1.EntityService.CreateEntity:input_type -> worldbuilder.entity.v1.CreateEntityRequest
	1,  // 12: worldbuilder.entity.v1.EntityService.GetEntity:output_type -> worldbuilder.entity.v1.GetEntityResponse
	3,  // 13: worldbuilder.entity.v1.EntityService.GetEntities:output_type -> worldbuilder.entity.v1.GetEntitiesResponse
	5,  // 14: worldbuilder.entity.v1.EntityService.CreateType:output_type -> worldbuilder.entity.v1.CreateTypeResponse
	7,  // 15: worldbuilder.entity.v1.EntityService.CreateEntity:output_type -> worldbuilder.entity.v1.CreateEntityResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_worldbuilder_entity_v1_entity_service_proto_init() }
func file_worldbuilder_entity_v1_entity_service_proto_init() {
	if File_worldbuilder_entity_v1_entity_service_proto != nil {
		return
	}
	file_worldbuilder_entity_v1_entity_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worldbuilder_entity_v1_entity_service_proto_rawDesc), len(file_worldbuilder_entity_v1_entity_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worldbuilder_entity_v1_entity_service_proto_goTypes,
		DependencyIndexes: file_worldbuilder_entity_v1_entity_service_proto_depIdxs,
		MessageInfos:      file_worldbuilder_entity_v1_entity_service_proto_msgTypes,
	}.Build()
	File_worldbuilder_entity_v1_entity_service_proto = out.File
	file_worldbuilder_entity_v1_entity_service_proto_goTypes = nil
	file_worldbuilder_entity_v1_entity_service_proto_depIdxs = nil
}
